spring:
    application:
        name: dinet
    
    flyway:
      enabled: true
      locations: classpath:db/migration
      baseline-on-migrate: true

    r2dbc:
        url: r2dbc:postgresql://localhost:5432/dbsolicitudes
        username: postgres
        password: root

server:
    address: 0.0.0.0
    port: 8086

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html